# These are supported funding model platforms

custom: ['https://www.buymeacoffee.com/Ottodix','https://www.paypal.com/donate/?business=LHYLTTECU7RSA&no_recurring=0&item_name=Hey%21+If+you+enjoyed+the+Eole+foobar+theme%2C+consider+donating+any+amount+you+feel+confortable+with%2C+it+would+make+my+day.+Thanks%21&currency_code=USD']
